### ISSUE TITLE
help the &porn command doesn't work 

### ISSUE THREAD

**Issue by nolife69** [whitetrashyt/r34discordbot#12]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\python\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "d:\python\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "d:\python\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object method can't be used in 'await' expression

**Comment by whitetrashyt** [comment]
Should be fixed in latest release. Let me know if that's incorrect.

**Comment by nolife69** [comment]
The same problem still occur i don't know why .
 The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\python\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "d:\python\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "d:\python\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object method can't be used in 'await' expression

**Comment by whitetrashyt** [comment]
Hey, sorry for the late reply! I'll get to looking into this as soon as i get an opening in my schedule.

**Comment by whitetrashyt** [comment]
Should be actually fixed this time, i fixed it on my personal release before the github release, my bad! should be fixed now.
